package fi.haagahelia.lautapelit.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

@Entity
public class Lautapeli {
	@Id	//Unique id for database
	@GeneratedValue(strategy=GenerationType.IDENTITY) //unique id automatically generated by database
	private long id;
	
	@Size(min = 1, max = 50, message = "Täytä nimi")
	private String nimi;
	private String tuotemerkki, isbn;
	
	@Min(value=1900, message = "Pienin sallittu on 1900")
	@Max(value=2022, message = "Suurin sallittu on 2022")
	private int vuosi;
	private double hinta;
	
	@ManyToOne
	@JoinColumn(name = "tyyppiId")
	private Tyyppi tyyppi;
	
	public Lautapeli() {
	}

	
	
	public Lautapeli(String nimi, String tuotemerkki, String isbn, int vuosi, double hinta) {
		super();
		this.nimi = nimi;
		this.tuotemerkki = tuotemerkki;
		this.isbn = isbn;
		this.vuosi = vuosi;
		this.hinta = hinta;
	}



	public Lautapeli(String nimi, String tuotemerkki, String isbn, int vuosi, double hinta, Tyyppi tyyppi) {
		super();
		this.nimi = nimi;
		this.tuotemerkki = tuotemerkki;
		this.isbn = isbn;
		this.vuosi = vuosi;
		this.hinta = hinta;
		this.tyyppi = tyyppi;
	}


	public Tyyppi getTyyppi() {
		return tyyppi;
	}


	public void setTyyppi(Tyyppi tyyppi) {
		this.tyyppi = tyyppi;
	}


	public void setTuotemerkki(String tuotemerkki) {
		this.tuotemerkki = tuotemerkki;
	}


	public long getId() {
		return id;
	}


	public void setId(long id) {
		this.id = id;
	}


	public String getNimi() {
		return nimi;
	}


	public void setNimi(String nimi) {
		this.nimi = nimi;
	}


	public String getTuotemerkki() {
		return tuotemerkki;
	}


	public void setTekija(String tuotemerkki) {
		this.tuotemerkki = tuotemerkki;
	}


	public String getIsbn() {
		return isbn;
	}


	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}


	public int getVuosi() {
		return vuosi;
	}


	public void setVuosi(int vuosi) {
		this.vuosi = vuosi;
	}


	public double getHinta() {
		return hinta;
	}


	public void setHinta(double hinta) {
		this.hinta = hinta;
	}


	@Override
	public String toString() {
		return "Lautapeli [id=" + id + ", nimi=" + nimi + ", tuotemerkki=" + tuotemerkki + ", isbn=" + isbn + ", vuosi=" + vuosi
				+ ", hinta=" + hinta + "]";
	}

	
	
}
